import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis, } from "recharts";
import { formatCurrency } from "../lib/utils";
const colors = ["#0f766e", "#2563eb", "#f59e0b", "#ef4444", "#7c3aed", "#14b8a6"];
export function RevenueChart({ data, mode, }) {
    return (_jsxs("div", { className: "card chart-card", children: [_jsx("div", { className: "section-title", children: _jsxs("div", { children: [_jsx("p", { className: "eyebrow", children: "Revenue over time" }), _jsxs("h3", { children: [mode[0].toUpperCase() + mode.slice(1), " trend"] })] }) }), _jsx(ResponsiveContainer, { width: "100%", height: 280, children: _jsxs(AreaChart, { data: data[mode], children: [_jsx("defs", { children: _jsxs("linearGradient", { id: "revenueFill", x1: "0", y1: "0", x2: "0", y2: "1", children: [_jsx("stop", { offset: "5%", stopColor: "#0f766e", stopOpacity: 0.24 }), _jsx("stop", { offset: "95%", stopColor: "#0f766e", stopOpacity: 0.02 })] }) }), _jsx(CartesianGrid, { vertical: false, stroke: "#e8ecef" }), _jsx(XAxis, { dataKey: "label", tickLine: false, axisLine: false }), _jsx(YAxis, { tickFormatter: (value) => `${Math.round(value / 1000)}k`, tickLine: false, axisLine: false }), _jsx(Tooltip, { formatter: (value) => formatCurrency(value) }), _jsx(Area, { type: "monotone", dataKey: "revenue", stroke: "#0f766e", fill: "url(#revenueFill)", strokeWidth: 2.5 })] }) })] }));
}
export function TableTypeChart({ data }) {
    return (_jsxs("div", { className: "card chart-card", children: [_jsx("div", { className: "section-title", children: _jsxs("div", { children: [_jsx("p", { className: "eyebrow", children: "Mix" }), _jsx("h3", { children: "Table type distribution" })] }) }), _jsx(ResponsiveContainer, { width: "100%", height: 280, children: _jsxs(PieChart, { children: [_jsx(Pie, { data: data, dataKey: "quantity", nameKey: "type", innerRadius: 66, outerRadius: 92, children: data.map((entry, index) => (_jsx(Cell, { fill: colors[index % colors.length] }, entry.type))) }), _jsx(Tooltip, {})] }) }), _jsx("div", { className: "legend-list", children: data.map((item, index) => (_jsxs("div", { className: "legend-row", children: [_jsx("span", { className: "legend-dot", style: { backgroundColor: colors[index % colors.length] } }), _jsx("span", { children: item.type }), _jsx("strong", { children: item.quantity })] }, item.type))) })] }));
}
export function SellerChart({ data }) {
    return (_jsxs("div", { className: "card chart-card", children: [_jsx("div", { className: "section-title", children: _jsxs("div", { children: [_jsx("p", { className: "eyebrow", children: "Performance" }), _jsx("h3", { children: "Seller revenue" })] }) }), _jsx(ResponsiveContainer, { width: "100%", height: 280, children: _jsxs(BarChart, { data: data, children: [_jsx(CartesianGrid, { vertical: false, stroke: "#e8ecef" }), _jsx(XAxis, { dataKey: "seller", tickLine: false, axisLine: false }), _jsx(YAxis, { tickFormatter: (value) => `${Math.round(value / 1000)}k`, tickLine: false, axisLine: false }), _jsx(Tooltip, { formatter: (value) => formatCurrency(value) }), _jsx(Bar, { dataKey: "revenue", fill: "#2563eb", radius: [10, 10, 0, 0] })] }) })] }));
}
